In [2]:
import pandas as pd
st1 = pd.Series({'국어':100,'영어':80,'수학':90})
st2 = pd.Series({'국어':90,'영어':80,'수학':80})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1/st2),2)
print(add,'\n')
print(sub,'\n')
print(mul,'\n')
print(div)

국어    190
영어    160
수학    170
dtype: int64 

국어    10
영어     0
수학    10
dtype: int64 

국어    9000
영어    6400
수학    7200
dtype: int64 

국어    1.11
영어    1.00
수학    1.12
dtype: float64


In [6]:
df = pd.concat([add,sub,mul,div],axis=1)
df

0   1     2     3
국어  190  10  9000  1.11
영어  160   0  6400  1.00
수학  170  10  7200  1.12

In [7]:
# result = pd.DataFrame([add,sub,mul,div],index=['덧셈','뺄셈','곱셈','나눗셈'])
result = pd.DataFrame([add,sub,mul,div])
result

국어      영어       수학
0   190.00   160.0   170.00
1    10.00     0.0    10.00
2  9000.00  6400.0  7200.00
3     1.11     1.0     1.12

In [9]:
import numpy as np
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1/st2),2)

result = pd.DataFrame([add,sub,mul,div],index=[b'덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [10]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

df2.loc[1,'b'] = np.nan
print(df1,'\n')
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [15]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [17]:
# fill_value()
# Q. df2의 NaN 값을 0으로 대체 후 사칙연산을 수행하세요.

add_data = df1.add(df2,fill_value=0)
sub_data = df1.sub(df2, fill_value=0)
mul_data = df1.mul(df2, fill_value=0)
div_data = df1.div(df2, fill_value=0)

print(add_data,'\n')
print(sub_data,'\n')
print(mul_data,'\n')
print(div_data)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0 

      a     b     c     d     e
0   0.0   0.0   0.0   0.0  -4.0
1  -1.0   5.0  -1.0  -1.0  -9.0
2  -2.0  -2.0  -2.0  -2.0 -14.0
3 -15.0 -16.0 -17.0 -18.0 -19.0 

      a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0   0.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0 

     a         b         c         d    e
0  NaN  1.000000  1.000000  1.000000  0.0
1  0.8       inf  0.857143  0.875000  0.0
2  0.8  0.818182  0.833333  0.846154  0.0
3  0.0  0.000000  0.000000  0.000000  0.0


In [18]:
arr = np.arange(12.).reshape(3,4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
arr[0]

array([0., 1., 2., 3.])

In [20]:
# broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [21]:
# DataFrame과 Series간 연산
df = pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('bde'),
                 index = ['서울','부산','인천','대구'])
df

b     d     e
서울  0.0   1.0   2.0
부산  3.0   4.0   5.0
인천  6.0   7.0   8.0
대구  9.0  10.0  11.0

In [22]:
sr = df.iloc[0]
sr

b    0.0
d    1.0
e    2.0
Name: 서울, dtype: float64

In [23]:
df - sr

b    d    e
서울  0.0  0.0  0.0
부산  3.0  3.0  3.0
인천  6.0  6.0  6.0
대구  9.0  9.0  9.0

In [14]:
# chatGPT 에러 : pandas broadcasting 적용 사례

import pandas as pd
import numpy as np

# 3x3 행렬 생성
df1 = pd.DataFrame(np.arange(1, 10).reshape(3, 3), columns=list('ABC'))

# 1x3 행렬 생성
df2 = pd.DataFrame([[10, 20, 30]], columns=list('ABC'))

# df1 출력
print("df1:\n", df1)

# df2 출력
print("\ndf2:\n", df2)

# df1과 df2의 합 구하기
result = df1 + df2

# result 출력
print("\nresult:\n", result)


df1:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

df2:
     A   B   C
0  10  20  30

result:
       A     B     C
0  11.0  22.0  33.0
1   NaN   NaN   NaN
2   NaN   NaN   NaN


In [15]:
import pandas as pd
import numpy as np

# 3x3 행렬 생성
df1 = pd.DataFrame(np.arange(1, 10).reshape(3, 3), columns=list('ABC'))

# 1x3 행렬 생성
df2 = pd.DataFrame([[10, 20, 30]], columns=list('ABC'))
sr2 = df2.iloc[0]
# df1 출력
print("df1:\n", df1)

# df2 출력
print("\nsr2:\n", sr2)

df1:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

sr2:
 A    10
B    20
C    30
Name: 0, dtype: int64


In [16]:
# df1과 sr2의 합 구하기
result = df1 + sr2

# result 출력
print("\nresult:\n", result)


result:
     A   B   C
0  11  22  33
1  14  25  36
2  17  28  39


In [25]:
# 함수 적용과 매핑
# randn은 표준정규분포에서 난수 생성
df = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                 index = ['서울','부산','인천','대구'])
df

b         d         e
서울  0.115774 -1.185147  1.633371
부산 -0.218589  0.655283 -0.333943
인천 -2.181973  2.137423 -0.638658
대구 -1.316923 -0.259066 -0.852543

In [26]:
np.abs(df)

b         d         e
서울  0.115774  1.185147  1.633371
부산  0.218589  0.655283  0.333943
인천  2.181973  2.137423  0.638658
대구  1.316923  0.259066  0.852543

커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map함수 : DataFrame 타입이 아니라, 반드시 Series 타입에서만 사용
- apply함수 : 커스텀 함수를 사용하기 위해 DataFrame에서 복수 개의 컬럼이 필요하다면, apply함수를 사용
- applymap함수 : DataFrame클래스의 함수이긴 하나, 위의 apply함수처럼 각 row(axis=1)나 각 column(axis=0)별로 
작동하는 함수가 아니라, 각 요소(element)별로 작동  
마치 선형대수에서 벡터에 스칼라를 연산하면, 벡터의 요소 하나하나에 해당 연산을 해주는 것처럼(elementwise) 
적용하는 DataFrame의 각 요소마다 커스텀 함수(반드시 Single vaule를 반환하는)를 수행한다고 보면 된다. 
applymap에 인자로 전달하는 커스텀함수가 Single value로부터 Single value를 반환한다는 점이 중요하다

In [27]:
# series의 최대값과 최소값의 차이를 계산
f = lambda x:x.max() - x.min()
df.apply(f)

b    2.297747
d    3.322570
e    2.485913
dtype: float64

In [28]:
# 각 행에 대해서 수행
df.apply(f,axis='columns')

서울    2.818517
부산    0.989226
인천    4.319396
대구    1.057857
dtype: float64

In [ ]:
# Q. 적절한 사용자 함수 혹은 람다 함수를 생성해서 df에 그 함수를 적용한 결과를 출력하세요.

In [31]:
f = lambda x: x.sum() / x.count()

a = np.abs(df).apply(f, axis = 1)
a

서울    0.978097
부산    0.402605
인천    1.652685
대구    0.809510
dtype: float64

In [37]:
a= lambda x:(x.max() + x.min())/2
# df.apply(a, axis='index')
df.apply(a)

b   -1.033099
d    0.476138
e    0.390414
dtype: float64

In [41]:
# 여러값을 가진 series 변환
def f(x):
    return pd.Series([x.min(),x.max()], index=['min','max'])

df.apply(f)

b         d         e
min -2.181973 -1.185147 -0.852543
max  0.115774  2.137423  1.633371

In [45]:
# Q. 실수값을 문자열 포맷으로 변환(소수점 2자리)

format = lambda x: '%.2f' %x
df.applymap(format)

b      d      e
서울   0.12  -1.19   1.63
부산  -0.22   0.66  -0.33
인천  -2.18   2.14  -0.64
대구  -1.32  -0.26  -0.85

In [47]:
# map함수는 series에만 적용

df['e'].map(format)

서울     1.63
부산    -0.33
인천    -0.64
대구    -0.85
Name: e, dtype: object