#### NumPy는 “Numerical Python“의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공
* Numerical Python을 의미하는 NumPy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
* 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
* 넘파이의 기본 데이터 타입은 ndarray. ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

NumPy 특징

- 강력한 N 차원 배열 객체
- 정교한 브로드케스팅(Broadcast) 기능
- C/C ++ 및 포트란 코드 통합 도구
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환(Fourier transform, FT)은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

Numpy Documentation  

https://numpy.org/doc/1.21/index.html

Numpy는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되었다.
- Numpy는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장
- Numpy의 각종 알고리즘은 모두 C로 작성되어 타입 검사나 다른 오버헤드 없이 메모리를 직접 조작
- Numpy 배열은 또한 내장 파이썬의 연속된 자료형들보다 훨씬 더 적은 메모리를 사용
- Numpy 연산은 파이썬 반복문을 사용하지 않고 전체 배열에 대한 복잡한 계산을 수행

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_array2 = my_arr * 2

Wall time: 14.3 ms


In [2]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 806 ms


In [9]:
# 배열 연산
np.random.seed(0)
data = np.random.randn(2,3)
print(data,'\n')
print(data * 10, '\n')
print(data + data)

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]] 

[[17.64052346  4.00157208  9.78737984]
 [22.40893199 18.6755799  -9.7727788 ]] 

[[ 3.52810469  0.80031442  1.95747597]
 [ 4.4817864   3.73511598 -1.95455576]]


In [11]:
print(data.shape) # 크기
print(data.dtype) # 자료형
print(data.ndim)  # 차원

(2, 3)
float64
2


In [12]:
# 배열 생성
# 1차원 배열
data1 = [6,7,5,8,0,1]
arr1 = np.array(data1)
print(arr1,type(arr1))

[6 7 5 8 0 1] <class 'numpy.ndarray'>


In [13]:
# 2차원 배열
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2,type(arr2),'\n')
print(arr2.shape,'\n')
print(arr2.ndim,'\n')
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> 

(2, 4) 

2 

int32


In [25]:
# 3차원 배열
data3 = [[[1,2,3,4,5],[6,7,8,9,10]],
        [[1,2,3,4,5],[6,7,8,9,10]],
        [[1,2,3,4,5],[6,7,8,9,10]]        ]
array3 = np.array(data3)
print(array3,type(array3))
print(array3.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] <class 'numpy.ndarray'>
(3, 2, 5)


배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [20]:
print(np.zeros(10),'\n')
print(np.zeros((3,5)),'\n')
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [21]:
print(np.ones(10),'\n')
print(np.ones((3,5)),'\n')
print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

In [22]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
# arange 함수 : 파이썬의 range 함수의 배열 버전
ar = np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
# reshape 함수
ar.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
# Q. array1에 reshape 함수를 이용 (5,2) 배열을 생성하고 형태를 같이 출력하세요.
array1 = np.arange(10)
array1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [34]:
# Q. ar에 reshpae() 함수 이용,  1차원, 2차원, 3차원 배열 생성
ar = np.arange(12)
print(ar.reshape(12), '\n')
print(ar.reshape(3,4), '\n')
print(ar.reshape(2,3,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [38]:
# 차원 변경
ar1 = np.arange(30)
print('1 -> 2,3차원')
ar12 = ar1.reshape(2,-1)
ar13 = ar1.reshape(-1,2,5)
print(ar12,'\n')
print(ar13)

1 -> 2,3차원
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [39]:
print('2 -> 1,3차원')
print(ar12,'\n')
ar21 = ar12.reshape(-1,)
ar23 = ar12.reshape(-1,2,5)
print(ar21,'\n')
print(ar23)

2 -> 1,3차원
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [40]:
print('3 -> 1,2차원')
ar31 = ar13.reshape(-1,)
ar32 = ar13.reshape(3,-1)
print(ar31,'\n')
print(ar32)

3 -> 1,2차원
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [42]:
ar3 = np.arange(30).reshape(3,2,5)
print(ar3,type(ar3),'\n')
l3 = ar3.tolist()
print(l3,type(l3))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] <class 'numpy.ndarray'> 

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]] <class 'list'>


행렬의 종류

https://math-development-geometry.tistory.com/52

- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 삼각행렬은 주대각선 원소를 기준으로 위 또는 아래에 있는 성분이 모두 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬

In [46]:
# 정방행렬
a = np.full((2,2),7)
a

array([[7, 7],
       [7, 7]])

In [47]:
# 항등행렬, 단위행렬
ar = np.eye(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
# 대각행렬
diag_mat = np.diag([1,2,3,4,5])
diag_mat

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [51]:
# 삼각행렬
upper_tri_mat = np.triu([[1,2,3],[4,5,6],[7,8,9]])
print(upper_tri_mat)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [ ]:
# [과제] 하삼각행렬을 생성하세요.